---
user: anton

dotfilesrepo: https://github.com/knechtling/dotfiles
dotfilesbranch: wayland
sucklessbranch: master

gitrepos:
  dwm: https://github.com/knechtling/wm.git
  st: https://github.com/knechtling/st
  dmenu: https://github.com/Lukesmithxyz/dmenu.git
  dwmblocks: https://github.com/knechtling/dwmblocks.git

additional_repos:
  autodeploy: https://github.com/knechtling/autodeploy
  dotfiles: https://github.com/knechtling/dotfiles

waylandrepos:
  dwl: https://github.com/knechtling/dwl.git
  slstatus: https://git.suckless.org/slstatus
  dwlmsg: https://codeberg.org/notchoc/dwlmsg.git

packages:
  - zsh
  - neovim
  - pacman
  - tmux
  - cowsay
  - xorg-server
  - xorg-xwininfo
  - xorg-xinit
  - polkit
  - ttf-linux-libertine
  - ttf-font-awesome
  - ttf-dejavu
  - ueberzug
  - bc
  - xcompmgr
  - xorg-xprop
  - arandr
  - dosfstools
  - libnotify
  - dunst
  - exfat-utils
  - sxiv
  - xwallpaper
  - ffmpeg
  - ffmpegthumbnailer
  - gnome-keyring
  - python-qdarkstyle
  - mpd
  - mpc
  - mpv
  - man-db
  - newsboat
  - noto-fonts
  - noto-fonts-emoji
  - ntfs-3g
  - wireplumber
  - pipewire-pulse
  - pulsemixer
  - maim
  - unclutter
  - unzip
  - xcape
  - xclip
  - xdotool
  - yt-dlp
  - zathura
  - zathura-pdf-mupdf
  - poppler
  - mediainfo
  - fzf
  - bat
  - xorg-xbacklight
  - slock
  - socat
  - moreutils
  - feh
  - firefox
  - ncdu
  - mathjax
  - bitwarden
  - ytfzf
  - shellcheck
  - rsync
  - qutebrowser
  - nextcloud-client
  - nmap
  - thunderbird
  - brightnessctl
  - stow
  - yajl    # json library needed for dwm IPC patch
  - lazygit
  - timeshift
  - arch-install-scripts
  - zsh
  - fakeroot
  - binutils
  - make
  - gcc
  - debugedit
  - automake
  - pkg-config
  - pango
  - freetype2

wayland_pkgs:
# Basics: these are needed to compile dwl
  - libinput
  - wayland
  - wlroots
  - libxkbcommon
  - wayland-protocols
  - pkg-config
  - fcft
  - tllist
# Extra features: notification daemon, wallpaper setter etc...
  - mako
  - swaybg
  - fcft
  - tllist
  - waylock 
  - wlroots
  - libxcb
  - xorg-xwayland
  - wmenu
  - foot
  - wdisplays
  - wl-clipboard
  - cliphist
  - wlr-which-key
  - xorg-xhost


aur_packages:
# zsh plugins
  - autojump
  - zsh-fast-syntax-highlighting-git
  - zsh-autosuggestions
  - zsh-history-substring-search
  - task-spooler-git
  - simple-mtpfs
  - feishin-bin
  - tmux-plugin-manager
  - yt-dlp-drop-in
  - xsettingsd
