---
dotfiles_branch: wayland

host_packages:
  - arch-install-scripts
  - brightnessctl
  - dosfstools
  - exfatprogs
  - gnome-keyring
  - lazygit
  - mediainfo
  - mpd
  - mpc
  - newsboat
  - nextcloud-client
  - ntfs-3g
  - qutebrowser
  - thunderbird
  - timeshift

host_aur_packages:
  - feishin-bin
  - simple-mtpfs
  - task-spooler-git
  - yt-dlp-drop-in
