---
dotfiles_branch: wayland

host_packages:
  - arch-install-scripts
  - brightnessctl
  - dosfstools
  - exfatprogs
  - gnome-keyring
  - lazygit
  - mediainfo
  - newsboat
  - nextcloud-client
  - ntfs-3g
  - qutebrowser
  - thunderbird

host_aur_packages:
  - batsignal
  - feishin-bin
  - lf-git
  - simple-mtpfs
  - task-spooler-git
  - yt-dlp-drop-in
