---
# VM-specific variables
hosttype: vm
dotfiles_branch: wayland

host_packages:
  - firefox

host_aur_packages: []

# Emptty configuration
emptty_enabled: true
emptty_autologin: true  # Convenient for testing VMs

# DO NOT degrade VMs
# No special scaling, no disabled animations
vm_optimizations: false
