---
wlroots_pkg: "{{ wlroots_pkg | default('wlroots0.19') }}"
wlroots_pkg_source: "{{ wlroots_pkg_source | default('repo') }}"
wlroots_version: "{{ (wlroots_pkg | regex_search('0\\.\\d+')) | default('') }}"
wlroots_pc_dir: "{{ '/usr/lib/wlroots-' + wlroots_version + '/pkgconfig' if wlroots_version else '/usr/lib/pkgconfig' }}"
wlroots_pc_file: "{{ wlroots_pc_dir + '/wlroots-' + wlroots_version + '.pc' if wlroots_version else '/usr/lib/pkgconfig/wlroots.pc' }}"

dwl_build_deps_base:
  - base-devel
  - pkgconf
  - wayland
  - wayland-protocols
  - libinput
  - libxkbcommon
  - seatd
  - fcft
  - tllist

# slstatus build settings
slstatus_repo: https://github.com/knechtling/slstatus.git
slstatus_branch: main
slstatus_src_dir: "/home/{{ user }}/.local/src/slstatus"
slstatus_install_prefix: /usr/local
slstatus_build_deps:
  - libx11
  - libxinerama

# Wallpaper defaults
dwl_wallpaper_candidates:
  - "{{ dwl_wallpaper_source | default('/home/' + user + '/.local/share/wallpapers/wallpaper.jpg') }}"
  - "/home/{{ user }}/.local/share/wallpapers/wallpaper.jpg"
  - "/home/{{ user }}/Pictures/wallpaper.jpg"
  - "/usr/share/backgrounds/archlinux/default.jpg"
dwl_wallpaper_target: "/home/{{ user }}/.local/share/dwl/wallpaper.jpg"
