---
wlroots_pkg: "{{ wlroots_pkg | default('wlroots0.19') }}"
wlroots_pkg_source: "{{ wlroots_pkg_source | default('repo') }}"
dwl_pkgconfig_dirs:
  - /usr/lib/pkgconfig
  - /usr/lib/wlroots-0.19/pkgconfig
  - /usr/lib/wlroots-0.18/pkgconfig
  - /usr/lib/wlroots-0.17/pkgconfig

dwl_build_deps_base:
  - base-devel
  - pkgconf
  - wayland
  - wayland-protocols
  - libinput
  - libxkbcommon
  - seatd
  - fcft
  - tllist
