---
wlroots_pkg: "{{ wlroots_pkg | default('wlroots') }}"
wlroots_pkg_source: "{{ wlroots_pkg_source | default('repo') }}"

dwl_build_deps_base:
  - base-devel
  - pkgconf
  - wayland
  - wayland-protocols
  - libinput
  - libxkbcommon
  - seatd
  - fcft
  - tllist
